---
- name: Change Wireguard Package Name (Zypper)
  tags: install
  set_fact: 
    WIREGUARD_PACKAGE:
      - "wireguard-tools"
  when: ansible_os_family in ["Suse"]

- name: Change Wireguard Package Name (DNF)
  tags: install
  set_fact: 
    WIREGUARD_PACKAGE:
      - "kmod-wireguard"
      - "wireguard-tools"
  when: ansible_os_family == "RedHat"

# Debian 10
- name: Install Buster Backports (Debian 10)
  tags: install
  apt_repository:
    repo: "{{ DEBIAN_BACKPORTS }}"
    state: present
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_major_version == "10"


# RHEL/CentOS 8


- name: Install Required Repositories (CentOS)
  tags: install
  dnf:
    pkg:
      - "{{ item }}"
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "8"
  loop: "{{ CENTOS_REPO_INSTALL }}"



# Install Wireguard 

- name: Install Wireguard Package
  tags: install
  package:
    name:
      - "{{ item }}"
    state: present
  loop: "{{ WIREGUARD_PACKAGE }}"