---
- name: Change Wireguard Package Name (Zypper)
  tags: install
  set_fact: 
    WIREGUARD_PACKAGE:
      - "wireguard-tools"
  when: ansible_os_family in ["Suse"]

- name: Change Wireguard Package Name (DNF)
  tags: install
  set_fact: 
    WIREGUARD_PACKAGE:
      - "kmod-wireguard"
      - "wireguard-tools"
  when: ansible_os_family in ["RedHat"]

# Debian 10
- name: Install Buster Backports (Debian 10)
  tags: install
  apt_repository:
    repo: "{{ DEBIAN_BACKPORTS }}"
    state: present
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_major_version == "10"

# RHEL 8
- name: Install elrepo and epel (RHEL 8)
  tags: install
  dnf:
    pkg: 
      - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm"
      - "https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm"
    disable_gpg_check: yes
  when:
    - ansible_distribution in ["RedHat"]
    - ansible_distribution_major_version == "8"

# CentOS 8


- name: Install Required Repositories (CentOS)
  tags: install
  dnf:
    pkg:
      - "{{ item }}"
  when:
    - ansible_distribution in ["CentOS", "AlmaLinux"]
    - ansible_distribution_major_version == "8"
  loop: "{{ CENTOS_REPO_INSTALL }}"



# Install Wireguard 

- name: Install Wireguard Package
  tags: install
  package:
    name:
      - "{{ item }}"
    state: present
  loop: "{{ WIREGUARD_PACKAGE }}"
